### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by afuyo** [HPI-Information-Systems/Metanome#395]
Hi, 
I run into this error:
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:bower (bower install) on project frontend: Failed to run task: 'bower install --quiet' 

[ERROR] bower angular-ui-router#~0.4.2 EINVRES Request to https://bower.herokuapp.com/packages/angular-ui-router failed with 502

Seems the package is deprecated. Where should that be configured? Any help appreciated.

> [INFO] --- frontend-maven-plugin:1.0:bower (bower install) @ frontend ---
[DEBUG] Configuring mojo com.github.eirslett:frontend-maven-plugin:1.0:bower from plugin realm ClassRealm[plugin>com.github.eirslett:frontend-maven-plugin:1.0, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:1.0:bower' with basic configurator -->
[DEBUG]   (f) arguments = install --quiet
[DEBUG]   (f) installDirectory = C:\playground\Metanome\frontend\target
[DEBUG]   (f) project = MavenProject: de.metanome:frontend:1.1-SNAPSHOT @ C:\playground\Metanome\frontend\pom.xml
[DEBUG]   (f) repositorySystemSession = org.eclipse.aether.DefaultRepositorySystemSession@545ddd5f
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@ecf9049
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipTests = false
[DEBUG]   (f) workingDirectory = C:\playground\Metanome\frontend\src
[DEBUG]   (f) execution = com.github.eirslett:frontend-maven-plugin:1.0:bower {execution: bower install}
[DEBUG] -- end configuration --
[INFO] Running 'bower install --quiet' in C:\playground\Metanome\frontend\src
[ERROR] bower angular-ui-router#~0.4.2 EINVRES Request to https://bower.herokuapp.com/packages/angular-ui-router failed with 502
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] metanome ........................................... SUCCESS [  5.041 s]
[INFO] test_helper ........................................ SUCCESS [  5.807 s]
[INFO] algorithm_integration .............................. SUCCESS [ 12.612 s]
[INFO] algorithm_helper ................................... SUCCESS [  4.484 s]
[INFO] algorithm_template ................................. SUCCESS [ 10.254 s]
[INFO] algorithm_template_root ............................ SUCCESS [  0.039 s]
[INFO] algorithm_template_packaging ....................... SUCCESS [  0.824 s]
[INFO] example_basic_stat_algorithm ....................... SUCCESS [  8.884 s]
[INFO] example_fd_algorithm ............................... SUCCESS [  7.460 s]
[INFO] example_ind_algorithm .............................. SUCCESS [  7.235 s]
[INFO] example_indirect_interfaces_algorithm .............. SUCCESS [  6.926 s]
[INFO] example_ucc_algorithm .............................. SUCCESS [  7.573 s]
[INFO] example_od_algorithm ............................... SUCCESS [  7.012 s]
[INFO] example_holistic_algorithm ......................... SUCCESS [  6.840 s]
[INFO] example_wrong_bootstrap_algorithm .................. SUCCESS [  6.176 s]
[INFO] example_relational_algorithm ....................... SUCCESS [  8.064 s]
[INFO] backend ............................................ SUCCESS [ 24.858 s]
[INFO] backendwar ......................................... SUCCESS [  3.834 s]
[INFO] example_cucc_algorithm ............................. SUCCESS [  9.788 s]
[INFO] example_sql_profiling_algorithm .................... SUCCESS [ 31.239 s]
[INFO] example_mvd_algorithm .............................. SUCCESS [ 10.274 s]
[INFO] example_dc_algorithm ............................... SUCCESS [  9.831 s]
[INFO] testing_algorithms ................................. SUCCESS [  0.083 s]
[INFO] frontend ........................................... FAILURE [07:08 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:24 min
[INFO] Finished at: 2018-06-27T21:56:33+02:00
[INFO] Final Memory: 97M/1254M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:bower (bower install) on project frontend: Failed to run task: 'bower install --quiet' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:bower (bower install) on project frontend: Failed to run task
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'bower install --quiet' failed. (error code 1)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
        at com.github.eirslett.maven.plugins.frontend.mojo.BowerMojo.execute(BowerMojo.java:42)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :frontend

**Comment by afuyo** [comment]
I managed to solve it. You need to add following lined in .bowerrc file:
{
  "directory": "bower_components",
  "registry": "https://registry.bower.io"
 
}

See Stackoverflow for reference
https://stackoverflow.com/questions/51020317/einvres-request-to-https-bower-herokuapp-com-packages-failed-with-502

**Comment by maxifischer** [comment]
Thanks for sharing this solution. I'll go with updating bower to the latest version, seems to be the cleaner version and fixes this issue for me. I'll fix it by tomorrow.
