### ISSUE TITLE
Metanome-cli failed in the TANE algorithm

### ISSUE THREAD

**Issue by MurikiGY** [HPI-Information-Systems/Metanome#437]
Im trying to use the TANE algorithm to find the functional dependencies in my csv file with the command:
```
java -cp metanome-cli-1.2-SNAPSHOT.jar:TANE-1.2-SNAPSHOT.jar de.metanome.cli.App --algorithm de.metanome.algorithms.tane --file-key INPUT_GENERATOR --files metanome_final.csv
```

but this is the output
```
file-key INPUT_GENERATOR --files metanome_final.csv
(metanome-cli) INFO     Running de.metanome.algorithms.tane
(metanome-cli) INFO     * in:            [metanome_final.csv]
(metanome-cli) INFO     * out:           file
(metanome-cli) INFO     * configuration: []
(metanome-cli) INFO     Initializing algorithm.
(metanome-cli) ERROR    Could not initialize algorithm.: java.lang.ClassNotFoundException: de.metanome.algorithms.tane
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:390)
	at java.base/java.lang.Class.forName(Class.java:381)
	at de.metanome.cli.App.createAlgorithm(App.java:242)
	at de.metanome.cli.App.configureAlgorithm(App.java:227)
	at de.metanome.cli.App.run(App.java:101)
	at de.metanome.cli.App.main(App.java:75)
```

What i'm doing wrong?

**Comment by sekruse** [comment]
The `--algorithm` parameter is wrong. It should be set to [`de.metanome.algorithms.tane.TaneAlgorithm`](https://github.com/HPI-Information-Systems/metanome-algorithms/blob/68d676594d921c59d0b1ce41f427f22d6c37015b/tane/tane_algorithm/src/main/java/de/metanome/algorithms/tane/TaneAlgorithm.java).
